// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envelopes.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createEnvelope = `-- name: CreateEnvelope :execresult
INSERT INTO envelopes (
    storage_key,
    metadata,
    envelope,
    request_hash,
    etag,
    feature_flags,
    expires_at,
    captcha_key_nonce,
    captcha_key_ciphertext
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEnvelopeParams struct {
	StorageKey           []byte       `db:"storage_key"`
	Metadata             []byte       `db:"metadata"`
	Envelope             []byte       `db:"envelope"`
	RequestHash          []byte       `db:"request_hash"`
	Etag                 string       `db:"etag"`
	FeatureFlags         uint32       `db:"feature_flags"`
	ExpiresAt            sql.NullTime `db:"expires_at"`
	CaptchaKeyNonce      []byte       `db:"captcha_key_nonce"`
	CaptchaKeyCiphertext []byte       `db:"captcha_key_ciphertext"`
}

func (q *Queries) CreateEnvelope(ctx context.Context, arg CreateEnvelopeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEnvelope,
		arg.StorageKey,
		arg.Metadata,
		arg.Envelope,
		arg.RequestHash,
		arg.Etag,
		arg.FeatureFlags,
		arg.ExpiresAt,
		arg.CaptchaKeyNonce,
		arg.CaptchaKeyCiphertext,
	)
}

const deleteEnvelopeByKey = `-- name: DeleteEnvelopeByKey :execrows
DELETE FROM envelopes
WHERE storage_key = ?
`

func (q *Queries) DeleteEnvelopeByKey(ctx context.Context, storageKey []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEnvelopeByKey, storageKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredEnvelopes = `-- name: DeleteExpiredEnvelopes :execrows
DELETE FROM envelopes
WHERE expires_at IS NOT NULL AND expires_at <= ?
ORDER BY expires_at
LIMIT ?
`

type DeleteExpiredEnvelopesParams struct {
	ExpiresAt sql.NullTime `db:"expires_at"`
	Limit     int32        `db:"limit"`
}

func (q *Queries) DeleteExpiredEnvelopes(ctx context.Context, arg DeleteExpiredEnvelopesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredEnvelopes, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEnvelopeByKey = `-- name: GetEnvelopeByKey :one
SELECT storage_key, metadata, envelope, request_hash, etag, feature_flags,
       expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
FROM envelopes
WHERE storage_key = ? AND (expires_at IS NULL OR expires_at > ?)
`

type GetEnvelopeByKeyParams struct {
	StorageKey []byte       `db:"storage_key"`
	ExpiresAt  sql.NullTime `db:"expires_at"`
}

func (q *Queries) GetEnvelopeByKey(ctx context.Context, arg GetEnvelopeByKeyParams) (Envelope, error) {
	row := q.db.QueryRowContext(ctx, getEnvelopeByKey, arg.StorageKey, arg.ExpiresAt)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvelopeForReplay = `-- name: GetEnvelopeForReplay :one
SELECT storage_key, metadata, envelope, request_hash, etag, feature_flags,
       expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
FROM envelopes
WHERE storage_key = ?
`

func (q *Queries) GetEnvelopeForReplay(ctx context.Context, storageKey []byte) (Envelope, error) {
	row := q.db.QueryRowContext(ctx, getEnvelopeForReplay, storageKey)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvelopeMetadataByKey = `-- name: GetEnvelopeMetadataByKey :one
SELECT metadata, feature_flags, expires_at
FROM envelopes
WHERE storage_key = ? AND (expires_at IS NULL OR expires_at > ?)
`

type GetEnvelopeMetadataByKeyParams struct {
	StorageKey []byte       `db:"storage_key"`
	ExpiresAt  sql.NullTime `db:"expires_at"`
}

type GetEnvelopeMetadataByKeyRow struct {
	Metadata     []byte       `db:"metadata"`
	FeatureFlags uint32       `db:"feature_flags"`
	ExpiresAt    sql.NullTime `db:"expires_at"`
}

func (q *Queries) GetEnvelopeMetadataByKey(ctx context.Context, arg GetEnvelopeMetadataByKeyParams) (GetEnvelopeMetadataByKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getEnvelopeMetadataByKey, arg.StorageKey, arg.ExpiresAt)
	var i GetEnvelopeMetadataByKeyRow
	err := row.Scan(&i.Metadata, &i.FeatureFlags, &i.ExpiresAt)
	return i, err
}

const lockEnvelopeByKey = `-- name: LockEnvelopeByKey :one
SELECT storage_key, metadata, envelope, request_hash, etag, feature_flags,
       expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
FROM envelopes
WHERE storage_key = ? AND (expires_at IS NULL OR expires_at > ?)
FOR UPDATE
`

type LockEnvelopeByKeyParams struct {
	StorageKey []byte       `db:"storage_key"`
	ExpiresAt  sql.NullTime `db:"expires_at"`
}

func (q *Queries) LockEnvelopeByKey(ctx context.Context, arg LockEnvelopeByKeyParams) (Envelope, error) {
	row := q.db.QueryRowContext(ctx, lockEnvelopeByKey, arg.StorageKey, arg.ExpiresAt)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}
