// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type Envelope struct {
	StorageKey           []byte       `db:"storage_key"`
	Metadata             []byte       `db:"metadata"`
	Envelope             []byte       `db:"envelope"`
	RequestHash          []byte       `db:"request_hash"`
	Etag                 string       `db:"etag"`
	FeatureFlags         uint32       `db:"feature_flags"`
	ExpiresAt            sql.NullTime `db:"expires_at"`
	CaptchaKeyNonce      []byte       `db:"captcha_key_nonce"`
	CaptchaKeyCiphertext []byte       `db:"captcha_key_ciphertext"`
	CreatedAt            time.Time    `db:"created_at"`
}
