// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envelopes.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnvelope = `-- name: ConsumeEnvelope :one
DELETE FROM envelopes
WHERE storage_key = $1 AND (expires_at IS NULL OR expires_at > $2)
RETURNING storage_key, metadata, envelope, request_hash, etag, feature_flags,
          expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
`

type ConsumeEnvelopeParams struct {
	StorageKey []byte             `db:"storage_key"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) ConsumeEnvelope(ctx context.Context, arg ConsumeEnvelopeParams) (Envelope, error) {
	row := q.db.QueryRow(ctx, consumeEnvelope, arg.StorageKey, arg.ExpiresAt)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const createEnvelope = `-- name: CreateEnvelope :one
INSERT INTO envelopes (
    storage_key,
    metadata,
    envelope,
    request_hash,
    etag,
    feature_flags,
    expires_at,
    captcha_key_nonce,
    captcha_key_ciphertext
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING storage_key, metadata, envelope, request_hash, etag, feature_flags,
          expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
`

type CreateEnvelopeParams struct {
	StorageKey           []byte             `db:"storage_key"`
	Metadata             []byte             `db:"metadata"`
	Envelope             []byte             `db:"envelope"`
	RequestHash          []byte             `db:"request_hash"`
	Etag                 string             `db:"etag"`
	FeatureFlags         int32              `db:"feature_flags"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at"`
	CaptchaKeyNonce      []byte             `db:"captcha_key_nonce"`
	CaptchaKeyCiphertext []byte             `db:"captcha_key_ciphertext"`
}

func (q *Queries) CreateEnvelope(ctx context.Context, arg CreateEnvelopeParams) (Envelope, error) {
	row := q.db.QueryRow(ctx, createEnvelope,
		arg.StorageKey,
		arg.Metadata,
		arg.Envelope,
		arg.RequestHash,
		arg.Etag,
		arg.FeatureFlags,
		arg.ExpiresAt,
		arg.CaptchaKeyNonce,
		arg.CaptchaKeyCiphertext,
	)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEnvelopes = `-- name: DeleteExpiredEnvelopes :many
WITH expired AS (
    SELECT envelopes.storage_key
    FROM envelopes
    WHERE envelopes.expires_at IS NOT NULL AND envelopes.expires_at <= $1
    ORDER BY envelopes.expires_at
    LIMIT $2
)
DELETE FROM envelopes AS target
USING expired
WHERE target.storage_key = expired.storage_key
RETURNING target.storage_key
`

type DeleteExpiredEnvelopesParams struct {
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
	BatchSize int32              `db:"batch_size"`
}

func (q *Queries) DeleteExpiredEnvelopes(ctx context.Context, arg DeleteExpiredEnvelopesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteExpiredEnvelopes, arg.ExpiresAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var storage_key []byte
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvelopeByKey = `-- name: GetEnvelopeByKey :one
SELECT storage_key, metadata, envelope, request_hash, etag, feature_flags,
       expires_at, captcha_key_nonce, captcha_key_ciphertext, created_at
FROM envelopes
WHERE storage_key = $1 AND (expires_at IS NULL OR expires_at > $2)
`

type GetEnvelopeByKeyParams struct {
	StorageKey []byte             `db:"storage_key"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) GetEnvelopeByKey(ctx context.Context, arg GetEnvelopeByKeyParams) (Envelope, error) {
	row := q.db.QueryRow(ctx, getEnvelopeByKey, arg.StorageKey, arg.ExpiresAt)
	var i Envelope
	err := row.Scan(
		&i.StorageKey,
		&i.Metadata,
		&i.Envelope,
		&i.RequestHash,
		&i.Etag,
		&i.FeatureFlags,
		&i.ExpiresAt,
		&i.CaptchaKeyNonce,
		&i.CaptchaKeyCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvelopeMetadataByKey = `-- name: GetEnvelopeMetadataByKey :one
SELECT metadata, feature_flags, expires_at
FROM envelopes
WHERE storage_key = $1 AND (expires_at IS NULL OR expires_at > $2)
`

type GetEnvelopeMetadataByKeyParams struct {
	StorageKey []byte             `db:"storage_key"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
}

type GetEnvelopeMetadataByKeyRow struct {
	Metadata     []byte             `db:"metadata"`
	FeatureFlags int32              `db:"feature_flags"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) GetEnvelopeMetadataByKey(ctx context.Context, arg GetEnvelopeMetadataByKeyParams) (GetEnvelopeMetadataByKeyRow, error) {
	row := q.db.QueryRow(ctx, getEnvelopeMetadataByKey, arg.StorageKey, arg.ExpiresAt)
	var i GetEnvelopeMetadataByKeyRow
	err := row.Scan(&i.Metadata, &i.FeatureFlags, &i.ExpiresAt)
	return i, err
}
