// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Envelope struct {
	StorageKey           []byte             `db:"storage_key"`
	Metadata             []byte             `db:"metadata"`
	Envelope             []byte             `db:"envelope"`
	RequestHash          []byte             `db:"request_hash"`
	Etag                 string             `db:"etag"`
	FeatureFlags         int32              `db:"feature_flags"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at"`
	CaptchaKeyNonce      []byte             `db:"captcha_key_nonce"`
	CaptchaKeyCiphertext []byte             `db:"captcha_key_ciphertext"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
}
